"""empty message

Revision ID: 36a5d64cb987
Revises: 1f463095c4f4
Create Date: 2024-01-09 20:23:18.570499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a5d64cb987'
down_revision: Union[str, None] = '1f463095c4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
constraint_unique_email: str = 'uq_constraint_users_email'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(constraint_unique_email, ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_unique_email, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
